---
- name: Manage User Account
  hosts: all
  become: true
  gather_facts: false
  tasks:
     - name: Create Users
       user:
         name: krishna
         shell: /bin/bash
         state: present
...         
