---
- name: Create User
  hosts: all
  become: true
  gather_facts: false
  tasks:
     - name: Create User Account As Argument Passed
       user:
        name: "{{ user_name }}"
        shell: /bin/bash
        state: present
       when: user_create == 'yes'
     - name: Delete User Account as Argument Passed
       user:
        name: "{{ user_name }}"
        state: absent
        remove: true
       when: user_create == 'no'
...         
